name: DnD LaTeX compilation
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: matsavage/dnd-latex-action@v0.3.0
        with:
          root_file: main.tex
